Update the Documentation
Froxlor/Froxlor.github.io pull request #2
Opened 2021-12-18 12:43 UTC by envoyr

New features are the hint in the footer that you can edit this page and will be redirected to the repository.

Furthermore, instructions were updated and marked as tested with the corresponding version.

Since there were outdated texts during the manual installation, they were revised again. There is still a lot of room for improvement, but this avoids using old techniques (libnss-mysql-bg, nscd, php-5) that are no longer actively used by Froxlor.

2021-12-18 14:04 UTC, d00p reviewed
Generally, the setting `PHP-FPM -> Alias folder of php-fpm configuration` is _not_ the directory for the pool-configs!!! This can be set in `admin -> PHP -> PHP-FPM versions`

2022-01-12 09:36 UTC, envoyr reviewed
Sorry for the late reply, i was a little bit busy. I have added some suggestions for improvement.

2022-01-12 09:36 UTC, envoyr commented on configuration/apache2/fcgid.md
> +/etc/init.d/cron start
```suggestion
service cron start
```

see `cron` comment above

2022-01-12 09:36 UTC, envoyr commented on configuration/apache2/php-fpm.md
> +/etc/init.d/cron stop
```suggestion
service cron stop
```

see `cron` comment above

2022-01-12 09:36 UTC, envoyr commented on configuration/apache2/php-fpm.md
> +/etc/init.d/cron start
```suggestion
service cron start
```

see `cron` comment above

2022-01-12 09:36 UTC, envoyr commented on configuration/nginx/php-fpm.md
> +/etc/init.d/cron start
```suggestion
service cron start
```

see `cron` comment above

2022-01-12 09:56 UTC, d00p requested changes
still adding local user is in there but it's based on a setting and is part of the config-templates

2022-01-12 09:56 UTC, d00p commented on configuration/apache2/fcgid.md
> +In order to use fcgid in Froxlor you need to create a `froxlorlocal` *user* and *group* of the same name:
The config-template do that according to the settings. The name of the local user can be changed in the settings

2022-01-12 09:56 UTC, d00p commented on configuration/apache2/fcgid.md
> +addgroup --gid 9999 froxlorlocal
well config-services script does the exact same commands as the configuration-templates show when doing it manually. So,adding the user is still included there

2022-01-12 09:56 UTC, d00p commented on configuration/apache2/php-fpm.md
> +addgroup --gid 9999 froxlorlocal
same as for the other one - not needed as it is included in the config-templates

2022-01-12 09:56 UTC, d00p commented on configuration/nginx/php-fpm.md
> +addgroup --gid 9999 froxlorlocal
also not required, part of config-templates

2022-01-12 09:56 UTC, d00p commented on configuration/nginx/php-fpm.md
> +addgroup --gid 9999 froxlorlocal
and again :)

2022-01-12 09:56 UTC, d00p commented on installation/debian.md
> +GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON froxlor.* TO 'froxlor'@'localhost';
why not just use `GRANT ALL PRIVILEGES...`?

2022-01-12 10:11 UTC, envoyr commented
Sorry I messed up the pull request a bit, I'm not that familiar with the reviews. Had given you a wrong version to review. 🙈 

> Generally, the setting `PHP-FPM -> Alias folder of php-fpm configuration` is _not_ the directory for the pool-configs!!! This can be set in `admin -> PHP -> PHP-FPM versions`

Should this info be deleted from the documentation?

2022-01-12 10:15 UTC, d00p commented
> Should this info be deleted from the documentation?

it's just important to note that the configuration path for the pool-files (domain-based settings) can be configured in `admin -> PHP -> PHP-FPM versions` and that `PHP-FPM -> Alias folder of php-fpm configuration` is just the wrong setting for that :)

2022-01-12 10:23 UTC, envoyr commented on configuration/apache2/fcgid.md
> +addgroup --gid 9999 froxlorlocal
Ahh i understand, didn't see that before. 👍

2022-01-12 10:58 UTC, envoyr reviewed
Updated in commit ed7f42a

2022-01-12 11:04 UTC, merged